version: '3.3'
services:

   nginx:
    build: ./nginx
    container_name: "nginx"
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - .:/app

   app:
    build: ./php
    container_name: "php"
    volumes:
      - .:/app
    depends_on:
      - mysql

   mysql:
    build: ./mysql
    restart: always
    container_name: "mysql"
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASS}
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
