version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
        environment:
          - APP_DEBUG: false
          - APP_ENV: local
          - DB_CONNECTION: mysql
          - DB_DATABASE: wanderlust
          - DB_USERNAME: ken
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: true
          - MYSQL_DATABASE: wanderlust
      # - image: circleci/node:8.9
    
    steps:
      - checkout
    
      - run: sudo apt update
      - run: sudo docker-php-ext-install pdo_mysql
 
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./app/composer.json" }}
            - v1-dependencies- 
      - save_cache:
          key: v1-dependencies-{{ checksum "./app/composer.json" }}
          paths:
            - ./app/vendor
 

      - run:
          name: Install GD library
          command: sudo apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev && sudo docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ && sudo docker-php-ext-install -j$(nproc) gd
      - run: composer install -n --prefer-dist --working-dir=./app
      - save_cache:
          key: composer-v1-{{ checksum "./app/composer.lock" }}
          paths:
            - ./app/vendor
     


      # - run: 
      #     name: npm preparation
      #     command: |
      #       curl -L git.io/nodebrew | perl - setup
      #       export PATH=$HOME/.nodebrew/current/bin:$PATH
      #       nodebrew setup
      #       nodebrew install-binary v8.9.3
      #       nodebrew use v8.9.3
      #       export PATH=$PATH:$HOME/.nodebrew/current/bin
      #       echo "export PATH=$PATH:$HOME/.nodebrew/current/bin" >> ~/.bash_profile
      #       which npm
      #       echo $HOME
      #       echo $PATH



      # - run: npm ci
      - restore_cache:
          key: npm-v1-{{ checksum "./app/package-lock.json" }}

      - run:
          name: npm ci
          working_directory: ./app
          command: |
            if [ ! -d node_modules ]; then
              npm ci 
            fi
      
      - save_cache:
          key: npm-v1-{{ checksum "./app/package-lock.json" }}
          paths:
            - node_modules

      - run: 
          name: npm run dev
          working_directory: ./app
          command: npm run dev

      - run: echo "APP_KEY=" > .env.testing
      - run: 
          name: php artisan key:generate
          working_directory: ./app
          command: php artisan key:generate
      - run: 
          name: php artisan migrate --seed
          working_directory: ./app
          command: php artisan migrate --seed

      - run:
          name: php test
          command: ./app/vendor/bin/phpunit