version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.2-browsers
        environment:
          - APP_DEBUG: false
          - APP_ENV: local
          - DB_CONNECTION: mysql
          - DB_DATABASE: wanderlust
          - DB_USERNAME: ken
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: true
          - MYSQL_DATABASE: wanderlust
    
    steps:
      - checkout
    
      - run: sudo apt update
      - run: sudo docker-php-ext-install pdo_mysql
 
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./app/composer.json" }}
            - v1-dependencies- 
      - run: sudo phpenmod gd
      - run:
          name: Install GD library
          command: sudo apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev && sudo docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ && sudo docker-php-ext-install -j$(nproc) gd
      - run: composer install -n --prefer-dist --working-dir=./app
      
     

      - save_cache:
          key: composer-v1-{{ checksum "./app/composer.lock" }}
          paths:
            - ./app/vendor
      - restore_cache:
          key: npm-v1-{{ checksum "./app/package-lock.json" }}




      - run: npm ci
      - run: npm run dev

 

      
      - save_cache:
          key: v1-dependencies-{{ checksum "./app/composer.json" }}
          paths:
            - ./app/vendor
 
      - run: echo "APP_KEY=" > .env.testing
      - run: php artisan key:generate
      - run: php artisan migrate --seed
      - run: ./app/vendor/bin/phpunit